### PR TITLE
Upgraded requests package version to 2.21.0 for #32.

### PR DESCRIPTION
**Pull request by acviana**
I know that this will probably be superseded by any work we do for #38 but this is a two-line fix that addresses a rather old security concern so I just wanted to patch it while we're doing some refactoring on this repo.

### CODE REVIEW

**Comment by acviana** [comment]
Uhh ... works on my machine?

**Comment by acviana** [comment]
So I'm stumped.

Every test that makes a connection test is failing under Python2.7 but only on Travis, not locally (at least not for me). They all raise the same exception (I think, there's like 150 failures):

```python
    def _request(self, method, url, data=None, **kwargs):
        try:
            response = self.session.request(method, url, data=data, **kwargs)
            if response.status_code == 200:
                return response
            else:
                try:
                    data = response.json()
                except ValueError:
                    data = None
                raise matchlight.error.APIError(
                    response.status_code, response.reason, data)
        except requests.exceptions.RetryError:
            raise matchlight.error.ConnectionError(
                'Matchlight API request failed with too many retries')
        except requests.exceptions.ConnectionError:
            raise matchlight.error.ConnectionError(
>               'Matchlight API request failed with connection error')
E           ConnectionError: Matchlight API request failed with connection error
```

Any ideas? Can anyone reproduce this?

**Comment by acviana** [comment]
Ok, progress, I created a new local virtualenv and I was able to reproduce the error.

**Comment by mattgeiger** [comment]
If I had to guess, it seems like that version of `httpretty` is unable to mock version 2.20.0 of `requests`. Unfortunately, we are using the latest version of `pytest-httpretty`.

I will take a look at this & see if I can at least narrow down the cause.

**Comment by acviana** [comment]
@mattgeiger yeah I came to the same conclusion. I looked through the github issues for the project and 1) doesn't seem to be getting many updates any more and 2) no mention of this specific issue that I could find.

I'm really hoping we don't have to write our tests just to update requests but this is making me think we probably want to move to a new testing framework anyway.

**Comment by cmeadows** [comment]
We should probably be using [responses](https://github.com/getsentry/responses) to test requests.

**Comment by acviana** [comment]
This is not solvable in it's currents state. Closing this is favor of the work in #73

**Pull request closed without merging**
